language: erlang

sudo: false
os: linux
otp_release:
  - 21.2
  - 20.3
  - 19.3
  - 18.3
  - 17.5

script: rebar3 eunit
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 as prod compile
  # - ./rebar3 as check xref
  # - ./rebar3 as check dialyzer
  - ./rebar3 eunit
  - ./rebar3 edoc

notifications:
  recipients:
    - hello@alind.io
